In [4]:
import pandas as pd

# 1. Đọc file dữ liệu
# Lưu ý: Đảm bảo file 'submissions.csv' nằm cùng thư mục với file notebook này
try:
    df = pd.read_csv('features_with_submissions.csv')
    print("✅ Đã tải file thành công!\n")
except FileNotFoundError:
    print("❌ Không tìm thấy file 'submissions.csv'. Hãy kiểm tra lại đường dẫn.")

# 2. Xem 5 dòng đầu tiên để có cái nhìn tổng quan
print("--- 5 Dòng đầu tiên của dữ liệu ---")
display(df.head())

# 3. Thông tin tổng quát về các đặc trưng (Số cột, kiểu dữ liệu, bộ nhớ)
print("\n--- Thông tin tổng quát (info) ---")
df.info()

# 4. Thống kê mô tả (Đối với các biến định lượng)
print("\n--- Thống kê mô tả (describe) ---")
display(df.describe())

# 5. Kiểm tra các giá trị bị thiếu (Missing values)
print("\n--- Số lượng giá trị thiếu trên mỗi đặc trưng ---")
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0] if missing_values.sum() > 0 else "Không có giá trị thiếu.")

# 6. Danh sách các cột (features)
print("\n--- Danh sách các đặc trưng hiện có ---")
print(df.columns.tolist())

✅ Đã tải file thành công!

--- 5 Dòng đầu tiên của dữ liệu ---

,adsh,tag,start,end,value,cik,sic,form,period,accepted,version,amendment_adsh,is_amended,ticker
0,121390024069010,NetIncomeLoss,2023-01-01,2023-06-30,141281.0,1934945.0,6770.0,10-Q,2024-06-30,2024-08-14 16:11:00,2024.0,0.0,False,tbmcu
1,121390024069010,NetIncomeLoss,2024-01-01,2024-06-30,589879.0,1934945.0,6770.0,10-Q,2024-06-30,2024-08-14 16:11:00,2024.0,0.0,False,tbmcu
2,121390024069010,NetIncomeLoss,2023-04-01,2023-06-30,390872.0,1934945.0,6770.0,10-Q,2024-06-30,2024-08-14 16:11:00,2024.0,0.0,False,tbmcu
3,121390024069010,NetIncomeLoss,2024-04-01,2024-06-30,217511.0,1934945.0,6770.0,10-Q,2024-06-30,2024-08-14 16:11:00,2024.0,0.0,False,tbmcu
4,121390024069010,NetIncomeLoss,2023-04-01,2023-06-30,0.0,1934945.0,6770.0,10-Q,2024-06-30,2024-08-14 16:11:00,2024.0,0.0,False,tbmcu

--- Thông tin tổng quát (info) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11289950 entries, 0 to 11289949
Data columns (total 14 columns):
 #   Column          Dtype
---  ------          -----
 0   adsh            int64
 1   tag             object
 2   start           object
 3   end             object
 4   value           float64
 5   cik             float64
 6   sic             float64
 7   form            object
 8   period          object
 9   accepted        object
 10  version         float64
 11  amendment_adsh  float64
 12  is_amended      object
 13  ticker          object
dtypes: float64(5), int64(1), object(8)
memory usage: 1.2+ GB

--- Thống kê mô tả (describe) ---

,adsh,value,cik,sic,version,amendment_adsh
count,1.128995e+07,1.128995e+07,1.128628e+07,1.128628e+07,1.128628e+07,1.128628e+07
mean,1.222155e+14,1.702250e+09,1.120225e+06,4.767964e+03,2.018313e+03,3.767332e+12
std,4.032831e+13,6.353508e+10,5.109515e+05,2.025690e+03,4.288139e+00,2.255192e+13
min,2.178110e+11,-1.658140e+14,1.750000e+03,0.000000e+00,2.008000e+03,0.000000e+00
25%,1.052918e+14,9.500000e+04,8.631100e+05,2.860000e+03,2.015000e+03,0.000000e+00
50%,1.213900e+14,1.410000e+07,1.158449e+06,4.700000e+03,2.019000e+03,0.000000e+00
75%,1.558370e+14,1.960000e+08,1.520358e+06,6.531000e+03,2.022000e+03,0.000000e+00
max,2.077096e+14,5.026300e+13,1.941536e+06,9.995000e+03,2.026000e+03,1.999371e+14

--- Số lượng giá trị thiếu trên mỗi đặc trưng ---
cik               3671
sic               3671
form              3671
period            3671
accepted          3671
version           3671
amendment_adsh    3671
is_amended        3671
ticker            3671
dtype: int64

--- Danh sách các đặc trưng hiện có ---
['adsh', 'tag', 'start', 'end', 'value', 'cik', 'sic', 'form', 'period', 'accepted', 'version', 'amendment_adsh', 'is_amended', 'ticker']

In [2]:
# Giả sử bạn đã đọc file vào biến df trước đó:
# df = pd.read_csv('submissions.csv')

# 1. Đếm số lượng các loại duy nhất (Số lượng loại)
num_types = df['form'].nunique()

# 2. Liệt kê danh sách các loại đó là gì
unique_types = df['form'].unique()

# 3. Xem mỗi loại xuất hiện bao nhiêu lần (Phân phối dữ liệu)
type_counts = df['form'].value_counts()

print(f"📌 Đặc trưng 'form' có tổng cộng: {num_types} loại.")
print(f"📌 Các loại cụ thể bao gồm: {unique_types}")
print("\n--- Chi tiết số lượng từng loại ---")
print(type_counts)

📌 Đặc trưng 'form' có tổng cộng: 4 loại.
📌 Các loại cụ thể bao gồm: ['10-Q' '10-K' '10-Q/A' '10-K/A']

--- Chi tiết số lượng từng loại ---
form
10-Q      198571
10-K       66288
10-Q/A      6256
10-K/A      5445
Name: count, dtype: int64

In [3]:
import pandas as pd

# Đọc hai file
features = pd.read_csv('features_selected.csv')
submissions = pd.read_csv('submissions.csv')

print(f"Shape features_selected: {features.shape}")
print(f"Shape submissions: {submissions.shape}")

# Kiểm tra cột adsh có tồn tại không
print("Columns in features:", features.columns.tolist())
print("Columns in submissions:", submissions.columns.tolist())

# Merge hai file trên adsh (left join để giữ tất cả features)
merged = pd.merge(
    features, 
    submissions, 
    on='adsh', 
    how='left'          # hoặc 'inner' nếu chỉ muốn các adsh có trong cả hai
)

print(f"✅ Đã merge thành công! Shape merged: {merged.shape}")

# Xem một vài dòng mẫu
print(merged.head())

# Lưu file kết quả
merged.to_csv('features_with_submissions.csv', index=False)
print("💾 Đã lưu file: features_with_submissions.csv")

Shape features_selected: (11289316, 5)
Shape submissions: (276560, 10)
Columns in features: ['adsh', 'tag', 'start', 'end', 'value']
Columns in submissions: ['adsh', 'cik', 'sic', 'form', 'period', 'accepted', 'version', 'amendment_adsh', 'is_amended', 'ticker']
✅ Đã merge thành công! Shape merged: (11289950, 14)
              adsh            tag       start         end     value  \
0  121390024069010  NetIncomeLoss  2023-01-01  2023-06-30  141281.0
1  121390024069010  NetIncomeLoss  2024-01-01  2024-06-30  589879.0
2  121390024069010  NetIncomeLoss  2023-04-01  2023-06-30  390872.0
3  121390024069010  NetIncomeLoss  2024-04-01  2024-06-30  217511.0
4  121390024069010  NetIncomeLoss  2023-04-01  2023-06-30       0.0

         cik     sic  form      period             accepted  version  \
0  1934945.0  6770.0  10-Q  2024-06-30  2024-08-14 16:11:00   2024.0
1  1934945.0  6770.0  10-Q  2024-06-30  2024-08-14 16:11:00   2024.0
2  1934945.0  6770.0  10-Q  2024-06-30  2024-08-14 16:11:00   2024.0
3  1934945.0  6770.0  10-Q  2024-06-30  2024-08-14 16:11:00   2024.0
4  1934945.0  6770.0  10-Q  2024-06-30  2024-08-14 16:11:00   2024.0

   amendment_adsh is_amended ticker
0             0.0      False  tbmcu
1             0.0      False  tbmcu
2             0.0      False  tbmcu
3             0.0      False  tbmcu
4             0.0      False  tbmcu
💾 Đã lưu file: features_with_submissions.csv

In [5]:
import pandas as pd

# Đọc file submissions
submissions = pd.read_csv('submissions.csv')

print(f"Original shape: {submissions.shape}")
print("Original columns:", submissions.columns.tolist())

# Danh sách cột muốn giữ
selected_columns = [
    'adsh', 
    'cik', 
    'sic', 
    'form', 
    'period', 
    'amendment_adsh', 
    'is_amended'
]

# Kiểm tra xem các cột có tồn tại không
missing_cols = [col for col in selected_columns if col not in submissions.columns]
if missing_cols:
    print(f"⚠️ Thiếu các cột sau: {missing_cols}")
else:
    # Tạo dataframe mới chỉ với các cột cần thiết
    submissions_clean = submissions[selected_columns].copy()
    
    print(f"✅ Đã tạo file mới với shape: {submissions_clean.shape}")
    print(submissions_clean.head())
    
    # Lưu file
    submissions_clean.to_csv('submissions_selected.csv', index=False)
    print("💾 Đã lưu file: submissions_selected.csv")

Original shape: (276560, 10)
Original columns: ['adsh', 'cik', 'sic', 'form', 'period', 'accepted', 'version', 'amendment_adsh', 'is_amended', 'ticker']
✅ Đã tạo file mới với shape: (276560, 7)
              adsh   cik   sic  form      period  amendment_adsh  is_amended
0  110465926033973  1750  3720  10-Q  2026-02-28               0       False
1  110465926001420  1750  3720  10-Q  2025-11-30               0       False
2  110465925092589  1750  3720  10-Q  2025-08-31               0       False
3  141057825001475  1750  3720  10-K  2025-05-31               0       False
4  141057825000519  1750  3720  10-Q  2025-02-28               0       False
💾 Đã lưu file: submissions_selected.csv

In [7]:
import pandas as pd

# Đọc file
df = pd.read_csv('features_selected.csv')

print(f"Original shape: {df.shape}")
print("Original columns:", df.columns.tolist())

# Các cột muốn giữ
selected_cols = ['adsh', 'tag', 'value']

# Kiểm tra cột có tồn tại không
missing = [col for col in selected_cols if col not in df.columns]
if missing:
    print(f"⚠️ Thiếu cột: {missing}")
else:
    # Tạo dataframe mới
    features_clean = df[selected_cols].copy()
    
    print(f"✅ Đã tạo file mới với shape: {features_clean.shape}")
    print(features_clean.head())
    
    # Lưu file
    features_clean.to_csv('features_adsh_tag_value.csv', index=False)
    print("💾 Đã lưu file: features_adsh_tag_value.csv")

Original shape: (11289316, 5)
Original columns: ['adsh', 'tag', 'start', 'end', 'value']
✅ Đã tạo file mới với shape: (11289316, 3)
              adsh            tag     value
0  121390024069010  NetIncomeLoss  141281.0
1  121390024069010  NetIncomeLoss  589879.0
2  121390024069010  NetIncomeLoss  390872.0
3  121390024069010  NetIncomeLoss  217511.0
4  121390024069010  NetIncomeLoss       0.0
💾 Đã lưu file: features_adsh_tag_value.csv

In [8]:
import pandas as pd

# Đọc hai file
submissions = pd.read_csv('submissions_selected.csv')
features = pd.read_csv('features_adsh_tag_value.csv')

print(f"Submissions shape: {submissions.shape}")
print(f"Features shape:    {features.shape}")

# Kết hợp hai bảng (mỗi adsh sẽ có nhiều tag/value)
merged = pd.merge(
    features,                    # Bảng chính (features)
    submissions,                 # Bảng bổ sung thông tin submission
    on='adsh',
    how='left'                   # Giữ tất cả các dòng features
)

print(f"✅ Merge hoàn tất! Shape merged: {merged.shape}")
print("\nCác cột sau khi merge:")
print(merged.columns.tolist())

# Xem mẫu 5 dòng đầu
print("\nSample data:")
print(merged.head())

# Sắp xếp cho dễ nhìn
merged = merged.sort_values(by=['adsh', 'tag'])

# Lưu file kết quả
merged.to_csv('features_with_submissions.csv', index=False)
print("\n💾 Đã lưu file: features_with_submissions.csv")

Submissions shape: (276560, 7)
Features shape:    (11289316, 3)
✅ Merge hoàn tất! Shape merged: (11289950, 9)

Các cột sau khi merge:
['adsh', 'tag', 'value', 'cik', 'sic', 'form', 'period', 'amendment_adsh', 'is_amended']

Sample data:
              adsh            tag     value        cik     sic  form  \
0  121390024069010  NetIncomeLoss  141281.0  1934945.0  6770.0  10-Q
1  121390024069010  NetIncomeLoss  589879.0  1934945.0  6770.0  10-Q
2  121390024069010  NetIncomeLoss  390872.0  1934945.0  6770.0  10-Q
3  121390024069010  NetIncomeLoss  217511.0  1934945.0  6770.0  10-Q
4  121390024069010  NetIncomeLoss       0.0  1934945.0  6770.0  10-Q

       period  amendment_adsh is_amended
0  2024-06-30             0.0      False
1  2024-06-30             0.0      False
2  2024-06-30             0.0      False
3  2024-06-30             0.0      False
4  2024-06-30             0.0      False

💾 Đã lưu file: features_with_submissions.csv

In [9]:
# Nếu bạn muốn dạng pivot (mỗi adsh một dòng, mỗi tag một cột)
pivot = merged.pivot_table(
    index=['adsh', 'cik', 'sic', 'form', 'period', 'amendment_adsh', 'is_amended'],
    columns='tag',
    values='value',
    aggfunc='first'          # nếu có trùng thì lấy cái đầu tiên
).reset_index()

pivot.to_csv('features_pivoted.csv', index=False)
print(f"Đã tạo file dạng wide: {pivot.shape}")

Đã tạo file dạng wide: (273113, 29)